apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: negd-uat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/ot-central-team/gitops.git'
        revision: HEAD
        files:
          - path: values/negd/uat/*-values.yaml
  template:
    metadata:
      name: 'negd-uat-{{trimSuffix "-values.yaml" .path.filename}}'
    spec:
      project: negd-uat-project
      source:
        repoURL: 'https://github.com/ot-central-team/gitops.git'
        targetRevision: HEAD
        path: helm
        helm:
          valueFiles:
            - values.yaml
            - ../values/negd/_tenant-defaults.yaml
            - ../{{.path.path}}/{{.path.filename}}
      destination:
        server: https://kubernetes.default.svc
        namespace: negd-uat
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
