apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Production Environment Security Boundary
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  sourceRepos:
    - 'https://github.com/asmabadrwork/gitops-manifests.git'
  destinations:
    - namespace: prod                    # <── Production Namespace!
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc