apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applications
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # <── Wave 1
spec:
  generators:
    - list:
        elements:
          # - app: python-demo-for-dashboard
          - app: python-demo-for-dashboard-bluegreen
          # - app: python-demo-for-dashboard-canary
  template:
    metadata:
      name: '{{app}}'
    spec:
      project: dev-project
      source:
        repoURL: 'https://github.com/ot-central-team/gitops.git'
        targetRevision: HEAD
        path: helm
        helm:
          valueFiles:
            - values.yaml
            - ../applications/dev/{{app}}-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
